### ISSUE TITLE
error setting

### ISSUE THREAD

**Issue by taufikhidayat1993** [fadidevv/react-native-fblogin#1]
![image](https://user-images.githubusercontent.com/38577145/63497007-23e4c800-c4ed-11e9-92ff-28c4f3176b46.png)

after success include username and password

**Comment by fadidevv** [comment]
Hello,

Please update to latest version v.10.5 if you did not updated yet and with assuming that you have already created Facebook App you have to add in your Facebook App Settings this **redirect_url:**

> https://facebook.com/connect/login_success.html 

**Note:** Facebook apps required this URL, also please read all steps in this repo carefully if needed.

**Should look like this:** 

<img width="1037" alt="react-native-fblogin-issue" src="https://user-images.githubusercontent.com/43948953/63515852-f82a0800-c515-11e9-9bd2-80c7b835c452.png">

Anything else please ask again.

Thank's!

**Comment by taufikhidayat1993** [comment]
thank you very much...your tutorial worked for me

**Comment by fadidevv** [comment]
You're welcome.

**Comment by taufikhidayat1993** [comment]
how to save after getinformation() data in  to my database

**Comment by fadidevv** [comment]
Hi,

getInformation() is function and returns JSON Object with 'User Facebook Account details' to save this data to Database you need to make API which receives 'application/json' body from client-side it's something that you have to figure out in your side if you cannot develop API you can hire someone to develop for you, Data you have you just need API connected with Database.

Thank's!
