### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by jagowm** [fadidevv/react-native-fblogin#2]
Hi, after the login in the facebook screen the response is:
Request failed with status code 400

I already put the secret key and appid

<img width="561" alt="Captura de Pantalla 2019-11-11 a la(s) 14 43 48" src="https://user-images.githubusercontent.com/17258085/68620113-71d8ee80-0492-11ea-9b26-27d24b5c9364.png">

thanks in advance!!!

<img width="1044" alt="Captura de Pantalla 2019-11-11 a la(s) 14 41 22" src="https://user-images.githubusercontent.com/17258085/68619603-6c2ed900-0491-11ea-83e8-340ff9f4d488.png">

**Comment by jagowm** [comment]
someone can help whit this issue???

**Comment by fadidevv** [comment]
> Hi, after the login in the facebook screen the response is:
> Request failed with status code 400
> 
> I already put the secret key and appid
> 
> <img alt="Captura de Pantalla 2019-11-11 a la(s) 14 43 48" width="561" src="https://user-images.githubusercontent.com/17258085/68620113-71d8ee80-0492-11ea-9b26-27d24b5c9364.png">
> 
> thanks in advance!!!
> 
> <img alt="Captura de Pantalla 2019-11-11 a la(s) 14 41 22" width="1044" src="https://user-images.githubusercontent.com/17258085/68619603-6c2ed900-0491-11ea-83e8-340ff9f4d488.png">

Hello,

Can you show me error from console you are getting?

Thank you.
