### ISSUE TITLE
WebView has been removed from React Native.

### ISSUE THREAD

**Issue by Multi-Thinker** [fadidevv/react-native-fblogin#3]
WebView has been removed from React Native. It can now be installed and imported from 'react-native-webview' instead of 'react-native'. See https://github.com/react-native-community/react-native-webview
- node_modules\react-native\Libraries\react-native\react-native-implementation.js:385:8 in Object.defineProperty$argument_2.get
- node_modules\@fadidev\react-native-fblogin\index.js:119:10 in Facebook#_commander
- node_modules\@fadidev\react-native-fblogin\index.js:204:11 in Facebook#render

**Comment by fadidevv** [comment]
Hello,

Thanks for the update, i know about this but i have no time to update it, i will do it no problem.

Thank you!
